# Generated by Django 4.1.5 on 2023-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction_App', '0011_alter_blacklist_workers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist_workers',
            name='count',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
