# Generated by Django 4.1.5 on 2023-05-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction_App', '0012_alter_blacklist_workers_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
