# Generated by Django 5.0.1 on 2024-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Construction_App', '0016_blacklist_workers_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
